controllers/LiveController.php
<?php
/**
 * @link      http://industrialax.com/
 * @email     xristmas365@gmail.com
 * @author    isteil
 * @copyright Copyright (c) 2020 INDUSTRIALAX SOLUTIONS LLC
 * @license   https://industrialax.com/license
 */

namespace app\controllers;

use yii\web\Controller;

class LiveController extends Controller
{

    /**
     * Displays Index Page.
     *
     * @return string
     */
    public function actionStream()
    {

    }
}

controllers/SignController.php
<?php
/**
 * @link      http://industrialax.com/
 * @email     xristmas365@gmail.com
 * @author    isteil
 * @copyright Copyright (c) 2020 INDUSTRIALAX SOLUTIONS LLC
 * @license   https://industrialax.com/license
 */

namespace app\controllers;

use app\modules\gym\models\Gym;
use app\modules\user\models\TrainerUp;
use app\modules\user\models\UserUp;
use Yii;
use yii\web\Response;
use yii\web\Controller;
use app\modules\user\models\SignIn;
use app\modules\user\models\SignUp;

class SignController extends Controller
{

    /**
     * Displays Index Page.
     *
     * @return string
     */
    public function actionIn()
    {
        $model = new SignIn();

        if($model->load(Yii::$app->request->post()) && $model->in()) {
            return $this->redirect(Yii::$app->getModule('user')->adminUrl);
        }

        return $this->render('in', ['model' => $model]);
    }

    /**
     * Sign up action.
     *
     * @return string|Response
     */
    public function actionUp()
    {
        $model = new SignUp;

        if($model->load(Yii::$app->request->post())) {
            if($model->signUp()) {

                return $this->redirect(['/admin/dashboard/index']);
            }

        }

        return $this->render('up', ['model' => $model]);
    }
	
	/**
	 * Sign up action.
	 *
	 * @return string|Response
	 */
	public function actionTrainerUp($auth)
	{
		$model = new TrainerUp;
		
		if($model->load(Yii::$app->request->post())) {
			if($model->signUp($auth)) {
		
				return $this->redirect(['/admin/dashboard/index']);
			}
		
		}
		
		return $this->render('trainerUp', ['model' => $model]);
	}
	
	/**
	 * Sign up action.
	 *
	 * @return string|Response
	 */
	public function actionJoin()
	{
		$model = new UserUp;
		$gym = Gym::items();
		
		if($model->load(Yii::$app->request->post())) {
			if($model->signUp()) {
				
				return $this->redirect(['/admin/dashboard/index']);
			}
			
		}
		
		return $this->render('userUp', [
			'model' => $model,
			'gym' => $gym,
		]);
	}

    /**
     * User Sign Out
     *
     * @return string
     */
    public function actionOut()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

controllers/SiteController.php
<?php
/**
 * @link      http://industrialax.com/
 * @email     xristmas365@gmail.com
 * @author    isteil
 * @copyright Copyright (c) 2020 INDUSTRIALAX SOLUTIONS LLC
 * @license   https://industrialax.com/license
 */

namespace app\controllers;

use Yii;
use yii\web\Controller;

class SiteController extends Controller
{
	
	/**
	 * Displays Index Page.
	 *
	 * @return string
	 */
	public function actionIndex()
	{
		/**
		 * SEO tags
		 */
		$view = Yii::$app->view;
		$view->title = Yii::$app->settings->main_title;
		$view->registerMetaTag(['name' => 'description', 'content' => Yii::$app->settings->main_description]);
		$view->registerMetaTag(['name' => 'keywords', 'content' => Yii::$app->settings->main_keywords]);
		
		return $this->render('index');
	}
	
	public function actionError()
	{
		$this->layout = YII_ENV == 'dev' ? false : 'main';
		$path = YII_ENV == 'dev' ? '@yii/views/errorHandler/exception.php' : '404';
		
		return $this->render($path, [
			'handler'   => Yii::$app->errorHandler,
			'exception' => Yii::$app->errorHandler->exception,
		]);
	}
}

views/sign/in.php
<?php
/**
 * @link      http://industrialax.com/
 * @email     xristmas365@gmail.com
 * @author    isteil
 * @copyright Copyright (c) 2020 INDUSTRIALAX SOLUTIONS LLC
 * @license   https://industrialax.com/license
 */

use yii\helpers\Html;
use kartik\form\ActiveForm;

?>


<div class="py-5 main-screen align-items-stretch">
	<?php $form = ActiveForm::begin() ?>
	
	<?= $form->field($model, 'email') ?>
	<?= $form->field($model, 'password')->passwordInput() ?>
	<?= $form->field($model, 'remember')->checkbox() ?>
	
	<?= Html::submitButton('Sign In', ['class' => 'btn btn-primary']) ?>
	
	<?php ActiveForm::end() ?>
</div>

views/sign/trainerUp.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
use app\modules\user\models\SignUp;
use yii\widgets\MaskedInput;

/* @var $this yii\web\View */

/* @var $form ActiveForm */

/* @var $model SignUp */

$this->title = 'Registration';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row d-flex justify-content-center mt-5">
    <div class="col-md-6">
      <div class="jumbotron">

        <h1 class="text-center">Welcome</h1>

        <hr>
          <?php $form = ActiveForm::begin() ?>

          <?= $form->field($model, 'email') ?>
	      
          <?= $form->field($model, 'first_name') ?>
          
	      <?= $form->field($model, 'last_name') ?>
	      
	      <?= $form->field($model, 'phone')->widget(MaskedInput::class, ['mask' => '999-999-9999', 'options' => ['placeholder' => '___-___-____']])?>

          <?= $form->field($model, 'password')->passwordInput() ?>

          <?= $form->field($model, 'passwordConfirm')->passwordInput() ?>

          <?= $form->field($model, 'rememberMe')->checkbox() ?>

          <?= Html::submitButton('Sign Up', ['class' => 'btn btn-primary btn-block']) ?>

          <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/sign/up.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
use app\modules\user\models\SignUp;

/* @var $this yii\web\View */

/* @var $form ActiveForm */

/* @var $model SignUp */

$this->title = 'Registration';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row d-flex justify-content-center mt-5">
    <div class="col-md-6">
      <div class="jumbotron">

        <h1 class="text-center">Welcome</h1>

        <hr>
          <?php $form = ActiveForm::begin() ?>

          <?= $form->field($model, 'email') ?>
	      
          <?= $form->field($model, 'first_name') ?>

          <?= $form->field($model, 'password')->passwordInput() ?>

          <?= $form->field($model, 'passwordConfirm')->passwordInput() ?>

          <?= $form->field($model, 'company') ?>

          <?= $form->field($model, 'rememberMe')->checkbox() ?>

          <?= Html::submitButton('Sign Up', ['class' => 'btn btn-primary btn-block']) ?>

          <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/sign/userUp.php
<?php

use yii\helpers\Html;
use kartik\form\ActiveForm;
use app\modules\user\models\SignUp;
use yii\widgets\MaskedInput;

/* @var $this yii\web\View */

/* @var $form ActiveForm */

/* @var $model SignUp */

/* @var $gym app\modules\gym\models\Gym */

$this->title = 'Registration';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row d-flex justify-content-center mt-5">
    <div class="col-md-6">
      <div class="jumbotron">

        <h1 class="text-center">Welcome</h1>

        <hr>
          <?php $form = ActiveForm::begin() ?>

          <?= $form->field($model, 'email') ?>
	      
          <?= $form->field($model, 'first_name') ?>
          
	      <?= $form->field($model, 'last_name') ?>
	      
	      <?= $form->field($model, 'phone')->widget(MaskedInput::class, ['mask' => '999-999-9999', 'options' => ['placeholder' => '___-___-____']])?>

          <?= $form->field($model, 'password')->passwordInput() ?>

          <?= $form->field($model, 'passwordConfirm')->passwordInput() ?>
         
          <?= $form->field($model, 'gym_id')->dropDownList($gym, ['prompt' => 'Select Gym']) ?>

          <?= $form->field($model, 'rememberMe')->checkbox() ?>

          <?= Html::submitButton('Sign Up', ['class' => 'btn btn-primary btn-block']) ?>

          <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

?>
<div class="site-index">
	<div class="jumbotron">
		<h1>Congratulations!</h1>
		<p>IndustrialAX-powered Application.</p>
		<p>
			<?php if(Yii::$app->user->isGuest) : ?>
				<?= Html::a('Sign Up', ['/sign/up'], ['class' => 'btn btn-primary']) ?>
				<?= Html::a('Sign In', ['/sign/in'], ['class' => 'btn btn-primary']) ?>
				<?= Html::a('Join', ['/sign/join'], ['class' => 'btn btn-primary']) ?>
			<?php else : ?>
				<?= Html::a('Dashboard', ['/admin/dashboard/index'], ['class' => 'btn btn-primary']) ?>
			<?php endif ?>
		
		</p>
	</div>
</div>